"""Synthetic lockfile data; never run Yarn, package scripts, or target code."""

from dataclasses import asdict
import json
from pathlib import Path

import pytest

from skylos.rules.sca import yarn_lockfile
from skylos.rules.sca.lockfile_types import LockfileLimitError, LockfileParseError
from skylos.rules.sca.yarn_lockfile import parse_yarn_lock


def parse(data, **kwargs):
    text = data if isinstance(data, str) else json.dumps(data)
    return parse_yarn_lock(Path("yarn.lock"), text=text, **kwargs)


def berry(packages=None, version=8):
    return {"__metadata": {"version": version}, **(packages or {})}


def package(name="pkg", version="1.0.0", **extra):
    return {
        "version": version,
        "resolution": f"{name}@npm:{version}",
        "linkType": "hard",
        **extra,
    }


def reasons(result):
    return {entry["reason"] for entry in result.unresolved}


CLASSIC = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

parent@^1.0.0:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/parent/-/parent-1.0.1.tgz#abc"
  dependencies:
    child "^1.0.0"
  optionalDependencies:
    child "^2.0.0"

child@^1.0.0, child@~1.0.0:
  version "1.0.2"
  resolved "https://registry.npmjs.org/child/-/child-1.0.2.tgz#abc"

"child@^2.0.0":
  version "2.0.3"
"""


def test_classic_multiple_versions_transitive_edges_and_optional_context():
    result = parse(CLASSIC)
    assert result.unresolved == []
    assert result.format_version == 1
    assert result.package_count == 3
    parent, child1, child2 = result.dependencies
    assert [dependency["line"] for dependency in result.dependencies] == [4, 12, 16]
    assert [dependency["version"] for dependency in result.dependencies] == [
        "1.0.1",
        "1.0.2",
        "2.0.3",
    ]
    assert parent["dependencies"][0]["package_path"] == child1["package_path"]
    assert parent["dependencies"][1]["package_path"] == child2["package_path"]
    assert parent["dependencies"][1]["optional"] is True
    assert child1["source_type"] == "npm_registry"
    assert child2["source_type"] == "registry_unspecified"
    assert all(
        dependency["dependency_kind"] == "unknown" for dependency in result.dependencies
    )
    assert all("dependency_dev" not in dependency for dependency in result.dependencies)


@pytest.mark.parametrize("version", [4, 6, 8])
def test_berry_workspaces_aliases_optional_peer_and_environment_context(version):
    result = parse(
        berry(
            {
                "app@workspace:.": {
                    "version": "0.0.0-use.local",
                    "resolution": "app@workspace:.",
                    "linkType": "soft",
                    "dependencies": {"alias": "npm:parent@^1", "local": "workspace:*"},
                },
                "local@workspace:*, local@workspace:packages/lib": {
                    "version": "0.0.0-use.local",
                    "resolution": "local@workspace:packages/lib",
                    "linkType": "soft",
                    "dependencies": {"child": "npm:^2"},
                    "dependenciesMeta": {"child": {"optional": True}},
                },
                "alias@npm:parent@^1": package(
                    "parent",
                    dependencies={"child": "npm:^1"},
                    peerDependencies={"react": "^18"},
                    peerDependenciesMeta={"react": {"optional": True}},
                ),
                "child@npm:^1": package("child"),
                "child@npm:^2": package(
                    "child", "2.0.0", conditions="os=darwin & cpu=arm64"
                ),
            },
            version,
        )
    )
    assert result.unresolved == []
    assert result.package_count == 5
    assert result.local_package_count == 2
    assert result.workspace_paths == ["", "packages/lib"]
    assert result.non_registry_names == ["app", "local"]
    parent, child1, child2 = result.dependencies
    assert parent["name"] == "parent"
    assert parent["dependency_kind"] == "direct"
    assert child1["dependency_kind"] == "transitive"
    assert child2["dependency_kinds"] == ["direct", "transitive"]
    assert child2["dependency_roots"] == ["", "packages/lib"]
    assert all(item["optional"] for item in child2["dependency_markers"]["yarn_usage"])
    assert child2["dependency_markers"]["conditions"] == "os=darwin & cpu=arm64"
    assert parent["dependencies"][1] == {
        "name": "react",
        "version_spec": "^18",
        "group": "peerDependencies",
        "optional": True,
    }
    assert "dependency_dev" not in parent
    assert all(
        dependency["environment_scope"] == "all_recorded"
        for dependency in result.dependencies
    )


def test_classic_scoped_alias_uses_actual_package_identity():
    result = parse("""# yarn lockfile v1
"alias@npm:@scope/real@^1":
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/@scope/real/-/real-1.2.3.tgz"
""")
    assert result.unresolved == []
    assert result.dependencies[0]["name"] == "@scope/real"


def test_classic_private_alias_records_both_names_without_source_url():
    result = parse("""# yarn lockfile v1
"alias@npm:real@^1":
  version "1.2.3"
  resolved "https://TOPSECRET@private.example/real/-/real-1.2.3.tgz"
""")
    assert result.dependencies == []
    assert result.non_registry_names == ["alias", "real"]
    assert "TOPSECRET" not in json.dumps(asdict(result))


@pytest.mark.parametrize("version", [4, 6])
def test_old_berry_bare_descriptor_normalization(version):
    result = parse(
        berry(
            {
                "parent@^1": package("parent", dependencies={"child": "npm:^1"}),
                "child@^1": package("child"),
            },
            version,
        )
    )
    assert result.unresolved == []
    assert (
        result.dependencies[0]["dependencies"][0]["package_path"]
        == result.dependencies[1]["package_path"]
    )


@pytest.mark.parametrize(
    "resolved",
    [
        "https://user:TOPSECRET@private.example/pkg/-/pkg-1.0.0.tgz",
        "https://registry.npmjs.org.private.example/pkg/-/pkg-1.0.0.tgz",
        "https://user:TOPSECRET@registry.npmjs.org/pkg/-/pkg-1.0.0.tgz",
        "https://registry.yarnpkg.com:443/pkg/-/pkg-1.0.0.tgz",
        "git+https://user:TOPSECRET@github.com/org/pkg.git",
    ],
)
def test_classic_non_public_sources_are_explicit_and_redacted(resolved):
    result = parse(
        f'# yarn lockfile v1\npkg@^1:\n  version "1.0.0"\n  resolved {json.dumps(resolved)}\n'
    )
    assert result.dependencies == []
    assert "non_registry_source" in reasons(result)
    assert result.non_registry_names == ["pkg"]
    assert resolved not in json.dumps(asdict(result))
    assert "TOPSECRET" not in json.dumps(asdict(result))


@pytest.mark.parametrize(
    "reference",
    [
        "https://user:TOPSECRET@private.example/archive.tgz",
        "git+https://user:TOPSECRET@github.com/org/pkg.git",
        "patch:pkg@npm%3A1.0.0#./secret.patch",
        "npm:1.0.0::__archiveUrl=https%3A%2F%2FTOPSECRET%40private.example",
        "virtual:abc#npm:1.0.0",
    ],
)
def test_berry_external_patched_or_unrecorded_peer_sources_remain_incomplete(reference):
    result = parse(berry({f"pkg@{reference}": package(resolution=f"pkg@{reference}")}))
    assert result.dependencies == []
    assert "non_registry_source" in reasons(result)
    output = json.dumps(asdict(result))
    assert "TOPSECRET" not in output
    assert "secret.patch" not in output


@pytest.mark.parametrize(
    "reference", ["file:../private", "link:../private", "workspace:packages/local"]
)
def test_classic_local_sources_counted_but_not_queried(reference):
    result = parse(f'# yarn lockfile v1\n"local@{reference}":\n  version "1.0.0"\n')
    assert result.dependencies == []
    assert result.local_package_count == 1
    assert result.non_registry_names == ["local"]
    assert reasons(result) == {"unsupported_package_source"}


@pytest.mark.parametrize(
    "root", ["../outside", "/outside", "a/../../outside", "C:/outside", "a\\b"]
)
def test_berry_invalid_workspace_path_is_not_followed(root):
    result = parse(
        berry(
            {
                "local@workspace:*": package(
                    "local", resolution=f"local@workspace:{root}", linkType="soft"
                )
            }
        )
    )
    assert result.dependencies == []
    assert result.workspace_paths == []
    assert reasons(result) == {"invalid_workspace_path"}


def test_missing_edges_and_invalid_metadata_keep_exact_inventory():
    result = parse(
        berry(
            {
                "pkg@npm:^1": package(
                    dependencies={"missing": "npm:^1", "bad": []},
                    peerDependencies="invalid",
                    dependenciesMeta={"missing": {"optional": "yes"}},
                    conditions=[],
                )
            }
        )
    )
    assert [dependency["name"] for dependency in result.dependencies] == ["pkg"]
    assert reasons(result) == {
        "missing_locked_dependency",
        "invalid_package_metadata",
        "invalid_dependency_declaration",
        "invalid_dependency_section",
    }


@pytest.mark.parametrize(
    "entry",
    [
        package(version="not-a-version"),
        package(resolution="pkg@npm:2.0.0"),
        package(resolution="other@npm:1.0.0"),
        package(linkType="soft"),
        package(resolution=False),
    ],
)
def test_invalid_or_conflicting_identity_is_never_guessed(entry):
    result = parse(berry({"pkg@npm:^1": entry}))
    assert result.dependencies == []
    assert result.unresolved


def test_external_descriptor_cannot_be_relabelled_as_public_resolution():
    result = parse(berry({"pkg@https://TOPSECRET@private.example/pkg.tgz": package()}))
    assert result.dependencies == []
    assert reasons(result) == {"non_registry_source"}
    assert "TOPSECRET" not in json.dumps(asdict(result))


@pytest.mark.parametrize("version", [1, 2, 3, 5, 7, 9, 10, 99, "8", True, None])
def test_unsupported_berry_version_is_explicit(version):
    with pytest.raises(LockfileParseError, match="unsupported"):
        parse(berry(version=version))


@pytest.mark.parametrize(
    "text",
    [
        "",
        "[]",
        "pkg: {}",
        "# yarn lockfile v2\n",
        '# yarn lockfile v1\npkg@^1:\n version "1.0.0"',
        '# yarn lockfile v1\npkg@^1:\n  version "1.0.0"\n  version "2.0.0"',
        '# yarn lockfile v1\npkg@^1:\n  version "1.0.0"\npkg@^1, pkg@~1:\n  version "1.0.0"',
        '# yarn lockfile v1\npkg@^1:\n  version "unterminated',
        '# yarn lockfile v1\npkg@^1:\n\tversion "1.0.0"',
        "__metadata: {version: 8}\nfoo: &anchor {}\nbar: *anchor",
        "__metadata: {version: 8}\npkg: !!python/object:thing {}",
        "__metadata: {version: 8}\n__metadata: {version: 8}",
        "__metadata: {version: 8}\n---\nother: document",
    ],
)
def test_malformed_data_rejected_without_execution(text):
    with pytest.raises(LockfileParseError):
        parse(text)


def test_empty_versioned_lockfiles():
    assert parse("# yarn lockfile v1\n").package_count == 0
    assert parse(berry()).package_count == 0


def test_line_locations_use_structure_not_version_string_search():
    result = parse("""# comment pkg version 1.0.0
__metadata:
  version: 8
"pkg@npm:^1":
  version: 1.0.0
  resolution: "pkg@npm:1.0.0"
  linkType: hard
"other@npm:^1":
  version: 1.0.0
  resolution: "other@npm:1.0.0"
""")
    assert [dependency["line"] for dependency in result.dependencies] == [4, 8]


def test_yaml_boolean_like_names_remain_strings():
    result = parse("""__metadata: {version: 8}
"yes@npm:^1":
  version: 1.0.0
  resolution: "yes@npm:1.0.0"
  dependencies:
    no: "npm:^1"
"no@npm:^1":
  version: 1.0.0
  resolution: "no@npm:1.0.0"
""")
    assert result.unresolved == []
    assert [dependency["name"] for dependency in result.dependencies] == ["yes", "no"]


def test_package_limit_counts_local_entries():
    with pytest.raises(LockfileLimitError):
        parse(
            berry({"app@workspace:.": {"resolution": "app@workspace:."}}),
            max_packages=0,
        )


def test_byte_limit(monkeypatch):
    monkeypatch.setattr(yarn_lockfile, "_MAX_BYTES", 10)
    with pytest.raises(LockfileLimitError):
        parse(CLASSIC)


def test_graph_work_limit(monkeypatch):
    monkeypatch.setattr(yarn_lockfile, "_MAX_GRAPH_WORK", 1)
    with pytest.raises(LockfileLimitError):
        parse(CLASSIC)


def test_classic_node_limit(monkeypatch):
    monkeypatch.setattr(yarn_lockfile, "_MAX_NODES", 2)
    with pytest.raises(LockfileLimitError):
        parse(CLASSIC)


def test_cyclic_graph_preserves_roots_and_terminates():
    result = parse(
        berry(
            {
                "app@workspace:.": {
                    "resolution": "app@workspace:.",
                    "dependencies": {"a": "npm:^1"},
                },
                "a@npm:^1": package("a", dependencies={"b": "npm:^1"}),
                "b@npm:^1": package("b", dependencies={"a": "npm:^1"}),
            }
        )
    )
    assert result.unresolved == []
    assert len(result.dependencies) == 2
    assert result.dependencies[0]["dependency_kinds"] == ["direct", "transitive"]
    assert all(
        dependency["dependency_roots"] == [""] for dependency in result.dependencies
    )


def test_invalid_decoded_unicode_raises_parse_error():
    with pytest.raises(LockfileParseError, match="UTF-8"):
        parse(berry({"pkg@\ud800": package()}))


def test_depth_limit():
    text = "__metadata: {version: 8}\nfoo: " + "[" * 70 + "0" + "]" * 70
    with pytest.raises(LockfileLimitError):
        parse(text)


def test_reader_uses_bounded_no_symlink_helper(monkeypatch):
    calls = []

    def read(path, **kwargs):
        calls.append((path, kwargs))
        return CLASSIC

    monkeypatch.setattr(yarn_lockfile, "read_text_no_symlink", read)
    assert parse_yarn_lock(Path("yarn.lock")).package_count == 3
    assert calls == [
        (Path("yarn.lock"), {"max_bytes": 10_000_000, "encoding": "utf-8"})
    ]
    monkeypatch.setattr(
        yarn_lockfile, "read_text_no_symlink", lambda *args, **kwargs: None
    )
    with pytest.raises(LockfileParseError, match="cannot be read"):
        parse_yarn_lock(Path("yarn.lock"))
