import ast
import json
import time
import tracemalloc

import pytest
from skylos.rules.secrets import (
    _yaml_checksum_context_spans,
    _yarn_integrity_spans,
    scan_ctx,
)

ELLIPSIS = "…"
NPM_SRI = (
    "sha512-qpw27gry1OuFb8xBSLkubCN12fvvzX68xMU+3hvGeOqMWyL3Pi0jEDWMSkyZBYyvIG"
    "0Bgx5Cg2BN1exHl33tIA=="
)
URLSAFE_NPM_SRI = NPM_SRI.replace("+", "_")
SHA256_SRI = "sha256-AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
SHA1_SRI = "sha1-vj1yZjK5l2Tkvlb7xTkbU4s5NPE="
_TWILIO_DIGEST_PREFIX = "SK" + ("0123456789abcdef" * 2)
TWILIO_SHAPED_SRI = (
    "sha512-"
    + _TWILIO_DIGEST_PREFIX
    + "+"
    + ("A" * (85 - len(_TWILIO_DIGEST_PREFIX)))
    + "=="
)
GENERIC_SECRET = "aB3dE5fG7hI9jK2lM4nO6pQ8rS0tU1vW2xY3zZ"
PURE_ALNUM_SECRET = "Z8k2Lm9Qp4Rs7Tv1Wx6Ya3Bc5De0Fg2H"
LOWERCASE_SHA256_HEX = "0123456789abcdef" * 4
YARN_V1_PREAMBLE = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
"""


def _ctx_from_source(src, rel="app.py", with_ast=False):
    if with_ast:
        tree = ast.parse(src)
    else:
        tree = None

    lines = src.splitlines(True)

    context = {"relpath": rel, "lines": lines, "tree": tree}

    return context


def _unicode_escape(value):
    return "".join(f"\\u{ord(character):04x}" for character in value)


def test_github_and_generic_both_fire_on_token_assignment():
    src = 'GITHUB_TOKEN = "ghp_1234567890abcdef1234567890abcdef1234"\n'

    findings = list(scan_ctx(_ctx_from_source(src)))

    providers = set()
    for finding in findings:
        provider_name = finding["provider"]
        providers.add(provider_name)

    assert "github" in providers
    assert "generic" in providers

    github_previews = []
    for finding in findings:
        if finding["provider"] == "github":
            preview = finding["preview"]
            github_previews.append(preview)

    assert len(github_previews) > 0
    first_preview = github_previews[0]
    assert first_preview.startswith("ghp_")
    assert ELLIPSIS in first_preview


@pytest.mark.parametrize(
    "line,provider",
    [
        ('GITLAB_PAT = "glpat-A1b2C3d4E5f6G7h8I9j0"\n', "gitlab"),
        ('SLACK_BOT = "xoxb-1234567890ABCDEF12"\n', "slack"),
        ('STRIPE = "sk_live_a1B2c3D4e5F6g7H8"\n', "stripe"),
        ('GOOGLE = "AIzaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"\n', "google_api_key"),
        ('SENDGRID = "SG.AAAAABBBBBCCCCCC.DDDDDEEEEEFFFFFFF"\n', "sendgrid"),
        ('TWILIO = "SK0123456789abcdef0123456789abcdef"\n', "twilio"),
        ('PK = "-----BEGIN RSA PRIVATE KEY-----"\n', "private_key_block"),
        ('AWS_ACCESS_KEY_ID = "AKIAABCDEFGHIJKLMNOP"\n', "aws_access_key_id"),
    ],
)
def test_provider_patterns(line, provider):
    findings = list(scan_ctx(_ctx_from_source(line)))
    assert any(f["provider"] == provider for f in findings)


def test_aws_secret_access_key_special_case():
    src = 'AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"\n'
    findings = list(scan_ctx(_ctx_from_source(src)))
    hit = None
    for finding in findings:
        if finding["provider"] == "aws_secret_access_key":
            hit = finding
            break

    assert hit is not None
    assert "entropy" in hit and isinstance(hit["entropy"], float)
    assert ELLIPSIS in hit["preview"]


def test_ignore_directive_suppresses_matches():
    src = 'GITHUB_TOKEN = "ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"  # skylos: ignore[SKY-S101]\n'
    findings = list(scan_ctx(_ctx_from_source(src)))
    assert findings == []


def test_allowlist_patterns_suppresses_line():
    src = 'TWILIO = "SKabcdefabcdefabcdefabcdefabcdefabcd"\n'
    allow = [r"TWILIO\s*="]
    findings = list(scan_ctx(_ctx_from_source(src), allowlist_patterns=allow))
    assert findings == []


def test_scan_comments_toggle():
    line = "# cred: xoxb-1234567890ABCDEF12 appears only in comment\n"
    findings_default = list(scan_ctx(_ctx_from_source(line)))

    found_slack = False
    for finding in findings_default:
        if finding["provider"] == "slack":
            found_slack = True
            break

    assert found_slack

    findings_off = list(scan_ctx(_ctx_from_source(line), scan_comments=False))
    assert findings_off == []


def test_scan_docstrings_toggle_with_ast():
    src = '''"""
module docstring with a GITHUB token: ghp_1234567890abcdef1234567890abcdef1234
"""
def f():
    """Function docstring with AWS AKIAABCDEFGHIJKLMNOP key."""
    return 1
'''
    f1 = list(scan_ctx(_ctx_from_source(src, with_ast=True)))
    providers_in_f1 = set()
    for finding in f1:
        provider_name = finding["provider"]
        providers_in_f1.add(provider_name)
    assert "github" in providers_in_f1 or "aws_access_key_id" in providers_in_f1

    f2 = list(scan_ctx(_ctx_from_source(src, with_ast=True), scan_docstrings=False))
    assert f2 == []


def test_suffix_and_path_filters():
    ctx_txt = _ctx_from_source(
        'X="ghp_1234567890abcdef1234567890abcdef1234"\n', rel="notes.txt"
    )
    assert list(scan_ctx(ctx_txt)) == []

    ctx_vendor = _ctx_from_source('X="AKIAABCDEFGHIJKLMNOP"\n', rel="vendor/app.py")
    out = list(scan_ctx(ctx_vendor, ignore_path_substrings=["vendor"]))
    assert out == []


def test_masking_behavior_short_and_long():
    short = 'X = "ABCDEFGH"\n'
    long = 'token = "ABCDEFGHIJKLMNOPKLMN"\n'

    short_findings = scan_ctx(_ctx_from_source(short))

    f_short = None
    for finding in short_findings:
        if finding["provider"] == "generic":
            f_short = finding
            break

    long_findings = scan_ctx(_ctx_from_source(long))

    f_long = None
    for finding in long_findings:
        if finding["provider"] == "generic":
            f_long = finding
            break

    assert f_short is None

    long_preview = f_long["preview"]
    starts_with_abcd = long_preview.startswith("ABCD")
    ends_with_klmn = long_preview.endswith("KLMN")
    contains_ellipsis = ELLIPSIS in long_preview

    assert starts_with_abcd and ends_with_klmn and contains_ellipsis


def test_safe_hints_suppress_detection():
    safe_line = 'EXAMPLE_TOKEN = "sk_test_this_is_example_value_not_real_123456"\n'
    out = list(scan_ctx(_ctx_from_source(safe_line)))
    assert out == []


def test_generic_is_suppressed_in_test_paths():
    src = 'X = "o2uV7Ew1kZ9Q3nR8sT5yU6pX4cJ2mL7a"\n'
    findings = list(scan_ctx(_ctx_from_source(src, rel="tests/unit/test_secrets.py")))

    generic_findings = []
    for f in findings:
        if f["provider"] == "generic":
            generic_findings.append(f)

    assert len(generic_findings) == 0


def test_normal_strings_ignored():
    src = 'X = "config_path"\n'
    ctx = _ctx_from_source(src)
    findings = list(scan_ctx(ctx))

    generic_findings = []
    for f in findings:
        if f["provider"] == "generic":
            generic_findings.append(f)

    assert len(generic_findings) == 0


def test_bare_generic_token_still_detected():
    token = "aB3dE5fG7hI9jK2lM4nO6pQ8rS0-tU1vW2xY3zZ"
    src = f"LEAKED = {token}\n"
    ctx = _ctx_from_source(src)

    generic = [f for f in scan_ctx(ctx) if f["provider"] == "generic"]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(token)


def test_ordered_character_set_enumeration_is_not_a_secret():
    src = (
        "UNRESERVED_CHARACTERS = (\n"
        '    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"\n'
        ")\n"
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_unsorted_character_set_lookalike_remains_detectable():
    token = "ModuleSymbhasOwnPr-0123456789ABCDEFGHNRVfgctiUvz_KqYTJkLxpZXIjQW"
    src = f'candidate = "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(token)

    static_findings = list(
        scan_ctx(
            _ctx_from_source(
                src,
                rel="mitmproxy/tools/web/static/vendor.js",
            )
        )
    )
    assert any(finding["rule_id"] == "SKY-S102" for finding in static_findings)


def test_ordered_character_set_under_secret_key_remains_detectable():
    token = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
    src = f'API_TOKEN = "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


@pytest.mark.parametrize(
    "token",
    [
        GENERIC_SECRET + "-01234567",
        (
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-"
            + GENERIC_SECRET
        ),
        "01234567ABCDEFGHaB3dE5fG7hJ9kL2a",
        "0123456-ABCDEFG-abcdefg-0123456-",
        (
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-."
            "aB3dE5fG7hI9jK2lM4nO6pQ8rS0tU1vW2xY3zZ"
        ),
        (
            "aB3dE5fG7hI9jK2lM4nO6pQ8rS0tU1vW2xY3zZ."
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
        ),
    ],
)
def test_ordered_runs_do_not_hide_bare_secret_lookalikes(token):
    src = f'candidate = "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


@pytest.mark.parametrize(
    "relpath,src",
    [
        (
            "reproduce.py",
            "integrity = sum(len(project.integrity_warnings) "
            "for project in report.projects)\n",
        ),
        ("app.py", "hash = calculate_digest(project.generated_contents)\n"),
        ("app.py", "checksum = values[artifact_key]\n"),
        ("app.ts", "const narHash = buildNarHash(pkg.derivationOutputs);\n"),
        ("app.js", "const contentHash = computeContentHash(asset.generatedBytes);\n"),
        (
            "app.py",
            "# integrity = sum(len(project.integrity_warnings) "
            "for project in report.projects)\n",
        ),
        (
            "app.py",
            'text = "integrity = sum(len(project.integrity_warnings) '
            'for project in report.projects)"\n',
        ),
        ("app.go", "checksum := calculateChecksum(artifactContents)\n"),
        ("app.rs", "let hash = calculate_hash(artifact_contents);\n"),
        ("app.dart", "final contentHash = calculateContentHash(assetBytes);\n"),
        ("app.js", "const integrity = `${computeIntegrity(payload)}`;\n"),
        (
            "app.ts",
            "const checksum = `checksum-${artifact.generatedIdentifier}`;\n",
        ),
        ("app.php", "$integrity = `calculate-integrity $artifact`;\n"),
        (
            "index.html",
            "<script>const integrity = calculateDigest(artifact.contents);</script>\n",
        ),
        (
            "index.html",
            "<script>const integrity = `${computeIntegrity(payload)}`;</script>\n",
        ),
        (
            "styles.css",
            "/* integrity = calculateDigest(project.generatedContents) */\n",
        ),
        ("metadata.yaml", "# integrity: calculateDigest(project.contents)\n"),
        (
            "metadata.yaml",
            'text: "integrity = calculateDigest(project.generatedContents)"\n',
        ),
        (
            "metadata.json",
            '{"text":"integrity = calculateDigest(project.generatedContents)"}\n',
        ),
        (
            "bundle.js.map",
            '{"text":"integrity = calculateDigest(project.generatedContents)"}\n',
        ),
    ],
)
def test_computed_checksum_fields_in_source_are_not_secrets(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "field",
    ["integrity", "hash", "checksum", "narHash", "contentHash"],
)
def test_quoted_checksum_fields_in_source_still_detect_secrets(field):
    token = "aB3dE5fG7hJ9$kL2mN4pQ"
    src = f'{field} = "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="app.py"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(token)
    assert generic[0]["end_col"] == src.index(token) + len(token)


@pytest.mark.parametrize(
    "relpath,src",
    [
        ("app.js", "const integrity = `aB3dE5fG7hJ9kL2mN4pQ`;\n"),
        (
            "app.js",
            "const integrity = `aB3dE5fG7hJ9kL2mN4pQ\\${literal}`;\n",
        ),
        (
            "app.js",
            "const integrity = `prefix\\`aB3dE5fG7hJ9$kL2mN4pQ`;\n",
        ),
        ("app.go", "checksum := `aB3dE5fG7hJ9kL2mN4pQ`\n"),
        (
            "app.go",
            "checksum := `aB3dE5fG7hJ9kL2mN4pQ${literal}`\n",
        ),
        (
            "index.html",
            "<script>const integrity = `aB3dE5fG7hJ9kL2mN4pQ`;</script>\n",
        ),
        ("app.js", "const integrity = `AbCdEfGhIjKlMnOpQrStUvWxYz`;\n"),
        ("app.go", "checksum := `AbCdEfGhIjKlMnOpQrStUvWxYz`\n"),
        (
            "index.html",
            "<script>const integrity = `AbCdEfGhIjKlMnOpQrStUvWxYz`;</script>\n",
        ),
    ],
)
def test_static_backtick_checksum_fields_still_detect_secrets(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


@pytest.mark.parametrize(
    "src,expected_line",
    [
        (
            "<script src=x integrity=aB3dE5fG7hJ9$kL2mN4pQ></script>\n",
            1,
        ),
        (
            "<script\n  integrity=aB3dE5fG7hJ9$kL2mN4pQ\n  src=x></script>\n",
            2,
        ),
    ],
)
def test_unquoted_html_integrity_values_still_detect_secrets(src, expected_line):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="index.html"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == expected_line


def test_html_attribute_text_is_not_mistaken_for_integrity_attribute():
    src = '<div data-note="integrity=aB3dE5fG7hJ9$kL2mN4pQ">metadata</div>\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="index.html"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_html_integrity_location_handles_mixed_cr_and_lf():
    token = "aB3dE5fG7hJ9$kL2mN4pQ"
    src = f"<div>one</div>\rnoise\n<script integrity={token}>\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="index.html"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 3
    assert generic[0]["col"] == src.splitlines()[2].index(token)


def test_html_context_budget_fails_closed(monkeypatch):
    monkeypatch.setattr("skylos.rules.secrets._MAX_JSON_CAPTURED_STRINGS", 1)
    src = (
        "<script integrity=aB3dE5fG7hJ9$kL2mN4pQ></script>\n"
        "<script integrity=bC4eF6gH8iK0$lM3nP5qR></script>\n"
    )

    findings = list(scan_ctx(_ctx_from_source(src, rel="index.html")))

    assert any(finding["rule_id"] == "SKY-ANALYSIS-INCOMPLETE" for finding in findings)


@pytest.mark.parametrize(
    "relpath,src",
    [
        ("metadata.yaml", "integrity: aB3dE5fG7hJ9$kL2mN4pQ\n"),
        ("metadata.yml", "HASH: aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (".env", "checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (
            ".env",
            "checksum=aB3dE5fG7hJ9#kL2mN4pQ\n",
        ),
        (
            ".env",
            "checksum=aB3dE5fG7hJ9$kL2mN4pQ  # deployment value\n",
        ),
        (".env", "  checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (".env", "checksum=`aB3dE5fG7hJ9$kL2mN4pQ`\n"),
        (".env", "checksum=#aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (".env", "'checksum'=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (".env", "export 'checksum'=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        ("example.env", "checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (".env.production", "export checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        ("settings.ini", "checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (
            "settings.ini",
            "checksum=aB3dE5fG7hJ9$kL2mN4pQ ; deployment value\n",
        ),
        (
            "settings.ini",
            "[artifact]\n  checksum=aB3dE5fG7hJ9$kL2mN4pQ\n",
        ),
        ("settings.ini", "checksum=`aB3dE5fG7hJ9$kL2mN4pQ`\n"),
        ("settings.ini", "checksum=;aB3dE5fG7hJ9$kL2mN4pQ\n"),
        ("settings.cfg", "NARHASH: aB3dE5fG7hJ9$kL2mN4pQ\n"),
        (
            "metadata.yaml",
            "- integrity: aB3dE5fG7hJ9$kL2mN4pQ\n",
        ),
        (
            "metadata.yaml",
            "metadata: {name: pkg, integrity: aB3dE5fG7hJ9$kL2mN4pQ}\n",
        ),
    ],
)
def test_unquoted_checksum_fields_in_data_files_still_detect_secrets(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


@pytest.mark.parametrize(
    "relpath,src",
    [
        ("metadata.yaml", f"hash: {LOWERCASE_SHA256_HEX}\n"),
        ("metadata.yaml", f"checksum: sha256:{LOWERCASE_SHA256_HEX}\n"),
        (".env", f"hash={LOWERCASE_SHA256_HEX}\n"),
        ("settings.ini", f"checksum={LOWERCASE_SHA256_HEX}\n"),
    ],
)
def test_conventional_unquoted_config_hashes_are_not_secrets(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "relpath,src",
    [
        ("metadata.yaml", f"integrity: {LOWERCASE_SHA256_HEX}\n"),
        (".env", f"integrity={LOWERCASE_SHA256_HEX}\n"),
    ],
)
def test_integrity_fields_do_not_inherit_hash_exemptions(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


def test_pnpm_wrong_path_integrity_does_not_inherit_hash_exemption():
    src = f"metadata:\n  integrity: {LOWERCASE_SHA256_HEX}\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


@pytest.mark.parametrize(
    "relpath,src",
    [
        (
            "metadata.yaml",
            "description: |\n"
            "  integrity = calculateDigest(project.generatedContents)\n",
        ),
        (
            "metadata.yaml",
            "integrity: >\n  calculateDigest(project.generatedContents)\n",
        ),
        (
            "metadata.yaml",
            "description: verify generated metadata,\n"
            "  integrity = calculateDigest(project.generatedContents)\n",
        ),
        (
            "metadata.toml",
            'description = """\n'
            "integrity = calculateDigest(project.generatedContents)\n"
            '"""\n',
        ),
        (
            "settings.ini",
            "[metadata]\n"
            "description = verify generated metadata\n"
            "  integrity = calculateDigest(project.generatedContents)\n",
        ),
        (
            ".env",
            "MESSAGE=verify package, integrity="
            "calculateDigest(project.generatedContents)\n",
        ),
        (
            ".env",
            "'message'=verify package, integrity="
            "calculateDigest(project.generatedContents)\n",
        ),
        (
            ".env",
            '"checksum"=calculateDigest(project.generatedContents)\n',
        ),
        (
            ".env",
            'MESSAGE="first line\nchecksum=aB3dE5fG7hJ9$kL2mN4pQ\n"\n',
        ),
    ],
)
def test_checksum_lookalikes_inside_multiline_or_other_values_are_clean(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "src",
    [
        (
            "defaults: &defaults\n"
            "  description: tagged metadata\n"
            "checksum: aB3dE5fG7hJ9$kL2mN4pQ\n"
        ),
        "description: !!str metadata\nhash: aB3dE5fG7hJ9$kL2mN4pQ\n",
        ("description: first\ndescription: second\nintegrity: aB3dE5fG7hJ9$kL2mN4pQ\n"),
        ("description: first document\n---\ncontentHash: aB3dE5fG7hJ9$kL2mN4pQ\n"),
    ],
)
def test_valid_yaml_features_do_not_disable_checksum_scanning(src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding.get("provider") == "generic"
    ]

    assert len(generic) == 1


def test_yaml_checksum_before_malformed_tail_is_still_scanned():
    src = "checksum: aB3dE5fG7hJ9$kL2mN4pQ\nbroken: [\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding.get("provider") == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 1


def test_deep_yaml_checksum_value_is_not_silently_skipped():
    token = "aB3dE5fG7hJ9$kL2mN4pQ"
    src = ("[" * 300) + f"{{integrity: {token}}}" + ("]" * 300) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


def test_malformed_yaml_before_checksum_fails_closed():
    src = "broken: [\nintegrity: aB3dE5fG7hJ9$kL2mN4pQ\n"

    findings = list(scan_ctx(_ctx_from_source(src, rel="metadata.yaml")))

    assert any(finding["rule_id"] == "SKY-ANALYSIS-INCOMPLETE" for finding in findings)


def test_yaml_context_budget_fails_closed(monkeypatch):
    monkeypatch.setattr("skylos.rules.secrets._MAX_GENERIC_YAML_EVENTS", 32)
    src = "items: [" + ("x, " * 40) + ("x]\nintegrity: aB3dE5fG7hJ9$kL2mN4pQ\n")

    findings = list(scan_ctx(_ctx_from_source(src, rel="metadata.yaml")))

    assert any(finding["rule_id"] == "SKY-ANALYSIS-INCOMPLETE" for finding in findings)


def test_yaml_checksum_alias_scans_the_anchored_scalar():
    src = "value: &artifact_hash aB3dE5fG7hJ9$kL2mN4pQ\nintegrity: *artifact_hash\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 1
    assert generic[0]["col"] == src.splitlines()[0].index("aB3")


def test_yaml_complex_key_does_not_leave_stale_checksum_state():
    src = (
        "? [integrity]\n"
        ": harmless\n"
        "checksum: aB3dE5fG7hJ9$kL2mN4pQ\n"
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 3


def test_yaml_scalar_alias_can_supply_checksum_mapping_key():
    src = (
        "field: &checksum_field integrity\n"
        "*checksum_field: aB3dE5fG7hJ9$kL2mN4pQ\n"
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 2


def test_yaml_aliases_do_not_cross_document_boundaries():
    src = (
        "value: &artifact_hash aB3dE5fG7hJ9$kL2mN4pQ\n---\nintegrity: *artifact_hash\n"
    )

    generic_contexts, decoded_contexts, incomplete_line = _yaml_checksum_context_spans(
        src.splitlines(True)
    )

    assert generic_contexts == {}
    assert decoded_contexts == {}
    assert incomplete_line is None


def test_generic_yaml_multiline_escape_cannot_hide_provider_signature():
    src = f'checksum: "S\\\n  {_TWILIO_DIGEST_PREFIX[1:]}"\n'

    providers = {
        finding["provider"]
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
    }

    assert "twilio" in providers


def test_many_yaml_checksum_fields_remain_bounded():
    token = "aB3dE5fG7hJ9$kL2mN4pQ"
    src = "items: [" + ", ".join(f"{{integrity: {token}}}" for _ in range(600)) + "]\n"

    started_at = time.perf_counter()
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="metadata.yaml"))
        if finding["provider"] == "generic"
    ]
    elapsed = time.perf_counter() - started_at

    assert len(generic) == 600
    assert elapsed < 2.0


def test_computed_checksum_field_does_not_hide_provider_secret():
    token = "ghp_" + "1234567890abcdef" * 2 + "1234"
    src = f'integrity = build("{token}")\n'

    providers = {finding["provider"] for finding in scan_ctx(_ctx_from_source(src))}

    assert "github" in providers


def test_dynamic_checksum_template_does_not_hide_provider_secret():
    token = "ghp_" + "1234567890abcdef" * 2 + "1234"
    src = (
        "const integrity = `prefix-${suffix}-"
        f"{token}`;\n"
    )

    providers = {
        finding["provider"] for finding in scan_ctx(_ctx_from_source(src, rel="app.js"))
    }

    assert "github" in providers


def test_dynamic_checksum_template_does_not_hide_long_bare_secret():
    src = f"const integrity = `${{prefix}}-{GENERIC_SECRET}`;\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="app.js"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    token_col = src.index(GENERIC_SECRET)
    assert generic[0]["col"] <= token_col < generic[0]["end_col"]


@pytest.mark.parametrize(
    "prefix",
    [
        "aB3dE5fG7hJ9$kL2mN4pQ",
        "AbCdEfGhIjKlMnOpQrStUvWxYz",
    ],
)
def test_dynamic_checksum_template_preserves_suspicious_literal_prefix(prefix):
    src = f"const integrity = `{prefix}-${{suffix}}`;\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="app.js"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(prefix)
    assert generic[0]["end_col"] == src.index("${")


@pytest.mark.parametrize(
    "src",
    [
        "const integrity = `integrity-checksum-for-build-${artifact.id}`;\n",
        "const integrity = `calculateIntegrityChecksum2-${artifact.id}`;\n",
        "const integrity = `integrity-sha256-checksum-${artifact.id}`;\n",
        "const integrity = `calculateSHA256Integrity-${artifact.id}`;\n",
        "const integrity = `sha512ChecksumGenerated-${artifact.id}`;\n",
        "const integrity = `contentHashV2ForDeployment-${artifact.id}`;\n",
        "const integrity = `version20260815Integrity-${artifact.id}`;\n",
    ],
)
def test_readable_dynamic_checksum_template_is_not_a_secret(src):

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="app.js"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_dotenv_backslash_does_not_suppress_next_assignment():
    src = "MESSAGE=abc\\\nchecksum=aB3dE5fG7hJ9$kL2mN4pQ\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=".env"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 2


def test_unterminated_dotenv_quote_recovers_later_assignment():
    src = 'MESSAGE="unterminated\nchecksum=aB3dE5fG7hJ9$kL2mN4pQ\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=".env"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["line"] == 2


def test_closed_dotenv_multiline_clears_pending_context_budget(monkeypatch):
    monkeypatch.setattr("skylos.rules.secrets._MAX_JSON_CAPTURED_STRINGS", 1)
    src = (
        'MESSAGE="first line\n'
        "checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"
        "integrity=bC4eF6gH8iK0$lM3nP5qR\n"
        '"\n'
        "checksum=cD5fG7hI9jL1$mN4pQ6rS\n"
    )

    findings = list(scan_ctx(_ctx_from_source(src, rel=".env")))
    generic = [finding for finding in findings if finding.get("provider") == "generic"]

    assert [finding["line"] for finding in generic] == [5]
    assert not any(
        finding["rule_id"] == "SKY-ANALYSIS-INCOMPLETE" for finding in findings
    )


def test_unterminated_dotenv_multiline_reports_first_context_overflow(monkeypatch):
    monkeypatch.setattr("skylos.rules.secrets._MAX_JSON_CAPTURED_STRINGS", 2)
    src = (
        'MESSAGE="unterminated\n'
        "checksum=aB3dE5fG7hJ9$kL2mN4pQ\n"
        "integrity=bC4eF6gH8iK0$lM3nP5qR\n"
        "narHash=cD5fG7hI9jL1$mN4pQ6rS\n"
    )

    findings = list(scan_ctx(_ctx_from_source(src, rel=".env")))
    generic = [finding for finding in findings if finding.get("provider") == "generic"]
    incomplete = [
        finding
        for finding in findings
        if finding["rule_id"] == "SKY-ANALYSIS-INCOMPLETE"
    ]

    assert [finding["line"] for finding in generic] == [2, 3]
    assert len(incomplete) == 1
    assert incomplete[0]["line"] == 4


def test_config_context_budget_fails_closed(monkeypatch):
    monkeypatch.setattr("skylos.rules.secrets._MAX_JSON_CAPTURED_STRINGS", 2)
    src = (
        "integrity=aB3dE5fG7hJ9$kL2mN4pQ\n"
        "narHash=bC4eF6gH8iK0$lM3nP5qR\n"
        "contentHash=cD5fG7hI9jL1$mN4pQ6rS\n"
    )

    findings = list(scan_ctx(_ctx_from_source(src, rel=".env")))

    assert any(finding["rule_id"] == "SKY-ANALYSIS-INCOMPLETE" for finding in findings)


def test_deep_computed_checksum_expression_is_bounded():
    expression = ("(" * 5_000) + "value" + (")" * 5_000)
    src = f"integrity = calculate({expression})\n"

    started_at = time.perf_counter()
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src))
        if finding["provider"] == "generic"
    ]
    elapsed = time.perf_counter() - started_at

    assert generic == []
    assert elapsed < 1.0


def test_generic_scan_handles_long_non_secret_token_without_quadratic_retry():
    src = ("a" * 12_000) + "\n"
    ctx = _ctx_from_source(src)

    started_at = time.perf_counter()
    findings = list(scan_ctx(ctx))
    elapsed = time.perf_counter() - started_at

    assert findings == []
    assert elapsed < 1.0


@pytest.mark.parametrize(
    "line,relpath",
    [
        (
            'sdist = { url = "https://files.pythonhosted.org/pkg.tar.gz", hash = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", size = 123 }',
            "uv.lock",
        ),
        (
            'checksum = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"',
            "Cargo.lock",
        ),
        (
            'files = [{file = "pkg.whl", hash = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}]',
            "poetry.lock",
        ),
        (
            'files = [{file = "pkg.whl", hash = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}]',
            "pdm.lock",
        ),
    ],
)
def test_known_lockfile_integrity_values_not_flagged_as_generic(line, relpath):
    src = line + "\n"
    ctx = _ctx_from_source(src, rel=relpath)
    generic = [f for f in scan_ctx(ctx) if f["provider"] == "generic"]
    assert generic == []


def test_yarn_invalid_integrity_value_remains_visible():
    src = (
        YARN_V1_PREAMBLE
        + "pkg@^1.0.0:\n"
        + '  version "1.0.0"\n'
        + "  integrity aB3dE5fG7hJ9$kL2mN4pQ\n"
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="yarn.lock"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1


@pytest.mark.parametrize(
    "src,expected_line",
    [
        (
            YARN_V1_PREAMBLE
            + "pkg@^1.0.0:\n"
            + '  version "1.0.0"\n'
            + f"  integrity {NPM_SRI}\n"
            + "  integrity aB3dE5fG7hJ9$kL2mN4pQ\n",
            6,
        ),
        ("  integrity aB3dE5fG7hJ9$kL2mN4pQ\n", 1),
    ],
)
def test_yarn_integrity_values_survive_invalid_structure(src, expected_line):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="yarn.lock"))
        if finding["provider"] == "generic"
    ]

    assert any(finding["line"] == expected_line for finding in generic)


@pytest.mark.parametrize(
    "relpath,field",
    [
        ("Cargo.lock", "checksum"),
        ("uv.lock", "hash"),
        ("poetry.lock", "hash"),
        ("pdm.lock", "hash"),
    ],
)
def test_mixed_case_lockfile_hash_lookalikes_remain_visible(relpath, field):
    src = f'{field} = "{GENERIC_SECRET}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "selector",
    [
        "pkg@^1.0.0",
        '"string-width-cjs@npm:string-width@^4.2.0"',
        '"pkg@git+ssh://git@github.com/org/repo.git#abc"',
        '"@scope/alias@npm:@scope/pkg@^1.0.0"',
    ],
)
def test_yarn_v1_package_integrity_is_not_flagged(selector):
    src = (
        YARN_V1_PREAMBLE
        + f"""
{selector}:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/pkg/-/pkg-1.0.0.tgz"
  integrity {NPM_SRI}
"""
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="yarn.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "src",
    [
        f"pkg@^1.0.0:\n  integrity {NPM_SRI}\n",
        f"# yarn lockfile v1\nmetadata:\n  integrity {NPM_SRI}\n",
        f"# yarn lockfile v1\npkg@^1.0.0:\n  note {NPM_SRI}\n",
        YARN_V1_PREAMBLE + f"pkg@^1:\n  integrity {NPM_SRI}\n",
        YARN_V1_PREAMBLE + f'pkg@^1:\n  version "1"\n integrity {NPM_SRI}\n',
        YARN_V1_PREAMBLE
        + f'pkg@^1:\n  version "1"\n  !garbage\n  integrity {NPM_SRI}\n',
        YARN_V1_PREAMBLE
        + (f'pkg@^1:\n  version "1"\n  integrity {NPM_SRI}\n  integrity {NPM_SRI}\n'),
        YARN_V1_PREAMBLE + f'pkg@^1:\n  version "1"\n  integrity {URLSAFE_NPM_SRI}\n',
    ],
)
def test_yarn_integrity_requires_v1_package_structure(src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="yarn.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "invalid_tail",
    [
        f"bad@^1:\n  integrity {NPM_SRI}\n",
        f'"pkg@^1":\n  version "1.0.0"\n  integrity {NPM_SRI}\n',
    ],
)
def test_invalid_yarn_tail_disables_all_earlier_approvals(invalid_tail):
    src = (
        YARN_V1_PREAMBLE
        + f'pkg@^1:\n  version "1.0.0"\n  integrity {NPM_SRI}\n'
        + invalid_tail
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="yarn.lock"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 2


def test_many_yarn_entries_keep_parser_memory_bounded():
    entry_count = 20_000
    lines = YARN_V1_PREAMBLE.splitlines(True) + [
        part
        for index in range(entry_count)
        for part in (
            f"pkg-{index}@^1:\n",
            '  version "1.0.0"\n',
            f"  integrity {NPM_SRI}\n",
        )
    ]

    tracemalloc.start()
    try:
        approved, contexts = _yarn_integrity_spans(lines)
        _, peak_bytes = tracemalloc.get_traced_memory()
    finally:
        tracemalloc.stop()

    assert len(approved) == entry_count
    assert contexts == {}
    assert peak_bytes < 16 * 1024 * 1024


@pytest.mark.parametrize(
    "package_key,descriptor,integrity",
    [
        (
            "pkg",
            "pkg@1.0.0",
            "sha512-nJhYv8z5ti1j2f7/Bt+4YN+j4/H0uDltKcAx0fBvGG0Fa9JEOv3UJ3e6qb1d5IqhvIiqoBs1XqAkONKvgjfG4Q==",
        ),
        (
            "alias",
            "real-pkg@1.2.3-beta.1",
            "sha512-nJhYv8z5ti1j2f7_Bt-4YN-j4_H0uDltKcAx0fBvGG0Fa9JEOv3UJ3e6qb1d5IqhvIiqoBs1XqAkONKvgjfG4Q",
        ),
        ("parent/@scope/child", "@scope/child@1.0.0", NPM_SRI),
    ],
)
def test_bun_package_integrity_is_not_flagged(package_key, descriptor, integrity):
    src = """{
  // Bun lockfiles are JSONC and permit trailing commas.
  "lockfileVersion": 0,
  "packages": {
    "PACKAGE_KEY": [
      "DESCRIPTOR",
      "",
      {"metadata": {"arch": "any"}},
      "INTEGRITY",
    ],
  },
}
"""
    src = (
        src.replace("PACKAGE_KEY", package_key)
        .replace("DESCRIPTOR", descriptor)
        .replace("INTEGRITY", integrity)
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="bun.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_bun_jsonc_line_comments_support_cr_only_lines():
    src = (
        "{\n"
        "  // generated lockfile\n"
        '  "lockfileVersion": 0,\n'
        '  "packages": {"pkg": ["pkg@1.0.0", "", {}, '
        f'"{NPM_SRI}"]}}\n'
        "}\n"
    ).replace("\n", "\r")

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="bun.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "payload",
    [
        {"lockfileVersion": 0, "secrets": {"pkg": ["pkg", "", {}, NPM_SRI]}},
        {
            "lockfileVersion": 0,
            "packages": {"pkg": ["pkg", "", NPM_SRI, "cache-key"]},
        },
        ["pkg", "", {}, NPM_SRI],
        {
            "lockfileVersion": 999,
            "packages": {"pkg": ["pkg", "", {}, NPM_SRI]},
        },
        {
            "lockfileVersion": 0.0,
            "packages": {"pkg": ["pkg", "", {}, NPM_SRI]},
        },
        {
            "lockfileVersion": 0,
            "packages": {"../metadata": ["pkg@1.0.0", "", {}, NPM_SRI]},
        },
        {
            "lockfileVersion": 0,
            "packages": {"metadata": ["not-a-descriptor", "", {}, NPM_SRI]},
        },
        {
            "lockfileVersion": 0,
            "packages": {"pkg": ["pkg@workspace:path", "", {}, NPM_SRI]},
        },
    ],
)
def test_bun_sri_requires_package_integrity_position(payload):
    src = json.dumps(payload, indent=2) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="bun.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic


def test_invalid_bun_package_integrity_stays_visible_as_one_candidate():
    src = json.dumps(
        {
            "lockfileVersion": 0,
            "packages": {"pkg": ["pkg@1.0.0", "", {}, PURE_ALNUM_SECRET]},
        }
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="bun.lock"))
        if finding["provider"] == "generic"
    ]

    assert [(finding["preview"], finding["col"]) for finding in generic] == [
        ("Z8k2…Fg2H", src.index(PURE_ALNUM_SECRET))
    ]


@pytest.mark.parametrize(
    "relpath,payload",
    [
        (
            "deno.lock",
            {
                "version": "5",
                "npm": {
                    "pkg@1.0.0": {"integrity": NPM_SRI},
                    "react-dom@18.3.1_react@18.3.1": {"integrity": NPM_SRI},
                    "@scope/pkg@1.0.0_peer@2.0.0": {"integrity": NPM_SRI},
                },
                "jsr": {"@std/assert@1.0.0": {"integrity": LOWERCASE_SHA256_HEX}},
            },
        ),
        (
            "deno.lock",
            {
                "version": "2",
                "npm": {"packages": {"zod@3.21.4": {"integrity": NPM_SRI}}},
            },
        ),
        (
            "deno.lock",
            {
                "version": "3",
                "packages": {
                    "npm": {"zod@3.23.8": {"integrity": NPM_SRI}},
                    "jsr": {
                        "@std/assert@1.0.0": {"integrity": f"5 {LOWERCASE_SHA256_HEX}"}
                    },
                },
            },
        ),
        (
            "flake.lock",
            {
                "version": 7,
                "nodes": {"root": {"locked": {"narHash": SHA256_SRI}}},
            },
        ),
        (
            "packages.lock.json",
            {
                "version": 1,
                "dependencies": {
                    "net8.0": {
                        "Example.Package": {"contentHash": NPM_SRI.split("-", 1)[1]}
                    }
                },
            },
        ),
        (
            "packages.demo.lock.json",
            {
                "version": 1,
                "dependencies": {
                    "net8.0": {
                        "Example.Package": {"contentHash": NPM_SRI.split("-", 1)[1]}
                    }
                },
            },
        ),
    ],
)
def test_structured_json_lockfile_integrity_is_not_flagged(relpath, payload):
    src = json.dumps(payload, indent=2) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "relpath,payload",
    [
        (
            "deno.lock",
            {"version": "999", "npm": {"pkg@1.0.0": {"integrity": NPM_SRI}}},
        ),
        (
            "flake.lock",
            {
                "version": 999,
                "nodes": {"root": {"locked": {"narHash": SHA256_SRI}}},
            },
        ),
        (
            "packages.lock.json",
            {
                "version": 999,
                "dependencies": {
                    "net8.0": {
                        "Example.Package": {"contentHash": NPM_SRI.split("-", 1)[1]}
                    }
                },
            },
        ),
    ],
)
def test_json_lockfile_integrity_requires_known_version(relpath, payload):
    src = json.dumps(payload, indent=2) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic


def test_deno_jsr_integrity_rejects_mixed_case_hex():
    src = json.dumps(
        {
            "version": "5",
            "jsr": {"@std/assert@1.0.0": {"integrity": LOWERCASE_SHA256_HEX.upper()}},
        }
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="deno.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "lockfile_version,package_id",
    [
        ("9.0", "pkg@1.0.0"),
        ("6.0", "/pkg@1.0.0"),
        ("6.1", "/pkg@1.0.0"),
        ("5.2", "/pkg/1.0.0"),
        ("5.4", "/pkg/1.0.0"),
    ],
)
def test_pnpm_package_integrity_is_not_flagged(lockfile_version, package_id):
    pytest.importorskip("yaml")
    src = f"""lockfileVersion: '{lockfile_version}'
packages:
  '{package_id}':
    resolution: {{integrity: {NPM_SRI}}}
"""

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_pnpm_v5_sha1_integrity_is_not_flagged():
    pytest.importorskip("yaml")
    src = f"""lockfileVersion: '5.4'
packages:
  /pkg/1.0.0:
    resolution: {{integrity: {SHA1_SRI}}}
"""

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize("lockfile_version", ["9.0", "999"])
def test_pnpm_unicode_escaped_integrity_uses_decoded_entropy(lockfile_version):
    pytest.importorskip("yaml")
    escaped_secret = _unicode_escape(PURE_ALNUM_SECRET)
    src = f"""lockfileVersion: '{lockfile_version}'
packages:
  'pkg@1.0.0':
    resolution:
      integrity: "{escaped_secret}"
"""

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]

    assert [finding["preview"] for finding in generic] == ["Z8k2…Fg2H"]


@pytest.mark.parametrize(
    "src",
    [
        f"lockfileVersion: '999'\npackages:\n  'pkg@1':\n    resolution: {{integrity: {NPM_SRI}}}\n",
        f"lockfileVersion: '9.0'\nmetadata:\n  integrity: {NPM_SRI}\n",
        f"lockfileVersion: '9.0'\npackages:\n  metadata:\n    resolution: {{integrity: {NPM_SRI}}}\n",
        (
            "lockfileVersion: '9.0'\n"
            "shared: &checksum "
            f"{NPM_SRI}\npackages:\n  'pkg@1':\n    resolution:\n"
            "      integrity: *checksum\n"
        ),
        (
            "lockfileVersion: '9.0'\n"
            f"shared: &checksum {PURE_ALNUM_SECRET}\n"
            "packages:\n  'pkg@1':\n    resolution:\n"
            "      integrity: *checksum\n"
        ),
        (
            "lockfileVersion: '9.0'\npackages:\n  'pkg@1':\n"
            f"    resolution:\n      integrity: !!str {PURE_ALNUM_SECRET}\n"
        ),
        (
            "lockfileVersion: '5.4'\npackages:\n  /pkg/1.0.0:\n"
            f"    resolution: {{integrity: {URLSAFE_NPM_SRI}}}\n"
        ),
    ],
)
def test_pnpm_integrity_requires_safe_structure(src):
    pytest.importorskip("yaml")
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]

    assert generic


def test_large_pnpm_lock_keeps_streaming_integrity_suppression():
    pytest.importorskip("yaml")
    src = (
        "lockfileVersion: '9.0'\nmetadata: "
        + ("A" * 600_000)
        + "\npackages:\n  'pkg@1.0.0':\n"
        + f"    resolution: {{integrity: {NPM_SRI}}}\n"
    )

    started_at = time.perf_counter()
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]
    elapsed = time.perf_counter() - started_at

    assert generic == []
    assert elapsed < 2.0


@pytest.mark.parametrize(
    "relpath,payload",
    [
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
        ),
        (
            "npm-shrinkwrap.json",
            {
                "name": "demo",
                "lockfileVersion": 1,
                "dependencies": {"pkg": {"integrity": NPM_SRI}},
            },
        ),
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 2,
                "packages": {"node_modules/fast-watch": {"integrity": SHA1_SRI}},
            },
        ),
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 1,
                "dependencies": {"legacy": {"integrity": SHA1_SRI}},
            },
        ),
        (
            "npm-shrinkwrap.json",
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
        ),
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 1,
                "dependencies": {
                    "parent": {"dependencies": {"child": {"integrity": NPM_SRI}}}
                },
            },
        ),
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 2,
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
                "dependencies": {"pkg": {"integrity": NPM_SRI}},
            },
        ),
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {
                    "node_modules/pkg": {"integrity": f"{NPM_SRI} {SHA256_SRI}"}
                },
            },
        ),
        (
            "package-lock.json",
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {
                    "node_modules/@scope/parent/node_modules/child": {
                        "integrity": NPM_SRI
                    }
                },
            },
        ),
    ],
)
def test_npm_lockfile_integrity_is_not_flagged(relpath, payload):
    src = json.dumps(payload, indent=2) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_compact_npm_lockfile_keeps_adjacent_secret_visible():
    src = json.dumps(
        {
            "name": "demo",
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            "api_key": GENERIC_SECRET,
        },
        separators=(",", ":"),
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert [(finding["preview"], finding["col"]) for finding in generic] == [
        ("aB3d…Y3zZ", src.index(GENERIC_SECRET))
    ]


@pytest.mark.parametrize(
    "src",
    [
        (
            '{"lockfileVersion":3,"lockfileVersion":3,"packages":{'
            f'"node_modules/pkg":{{"integrity":"{NPM_SRI}"}}}}}}'
        ),
        (
            '{"lockfileVersion":3,"packages":{"node_modules/pkg":{'
            f'"integrity":"{NPM_SRI}","integrity":"{NPM_SRI}"}}}}}}'
        ),
    ],
)
def test_duplicate_npm_json_keys_disable_integrity_suppression(src):
    src += "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert generic


def test_npm_integrity_approval_is_bound_to_exact_json_position():
    note = f" integrity: '{NPM_SRI}'"
    src = json.dumps(
        {
            "name": "demo",
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            "note": note,
        },
        indent=2,
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert [(finding["preview"], finding["line"]) for finding in generic] == [
        ("sha5…IA==", src[: src.index(note)].count("\n") + 1)
    ]


@pytest.mark.parametrize(
    "src",
    [
        json.dumps(
            {
                "lockfileVersion": 3,
                "packages": {"node_modules/pkg": {"integrity": PURE_ALNUM_SECRET}},
            }
        ),
        (
            '{"lockfileVersion":3,"packages":{"node_modules/pkg":{'
            f'"integri\\u0074y":"{PURE_ALNUM_SECRET}"}}}}}}'
        ),
        json.dumps(
            {
                "lockfileVersion": 3,
                "metadata": {"integrity": PURE_ALNUM_SECRET},
            }
        ),
        (
            '{"lockfileVersion":3,"metadata":{'
            f'"integri\\u0074y":"{PURE_ALNUM_SECRET}"}}}}'
        ),
    ],
)
def test_invalid_or_wrong_path_integrity_values_remain_contextual(src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert [(finding["preview"], finding["col"]) for finding in generic] == [
        ("Z8k2…Fg2H", src.index(PURE_ALNUM_SECRET))
    ]


@pytest.mark.parametrize("path", ["approved", "metadata"])
def test_unicode_escaped_integrity_value_uses_decoded_entropy(path):
    escaped_secret = _unicode_escape(PURE_ALNUM_SECRET)
    if path == "approved":
        body = f'"packages":{{"node_modules/pkg":{{"integrity":"{escaped_secret}"}}}}'
    else:
        body = f'"metadata":{{"integrity":"{escaped_secret}"}}'
    src = f'{{"lockfileVersion":3,{body}}}'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert [finding["preview"] for finding in generic] == ["Z8k2…Fg2H"]


def test_provider_signatures_remain_visible_inside_approved_checksum():
    src = json.dumps(
        {
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": TWILIO_SHAPED_SRI}},
            "metadata": {"integrity": TWILIO_SHAPED_SRI},
        },
        indent=2,
    )

    findings = list(scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json")))

    assert [finding["provider"] for finding in findings].count("twilio") == 2


@pytest.mark.parametrize(
    "provider_token,provider",
    [
        ("AKIA" + ("A" * 16), "aws_access_key_id"),
        ("AIza" + ("A" * 35), "google_api_key"),
        ("SK" + ("a" * 32), "twilio"),
    ],
)
def test_provider_signature_inside_checksum_digest_remains_visible(
    provider_token, provider
):
    digest = "A" + provider_token + ("A" * (85 - len(provider_token)))
    integrity = f"sha512-{digest}=="
    src = json.dumps(
        {
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": integrity}},
        }
    )

    findings = list(scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json")))

    assert [finding["provider"] for finding in findings].count(provider) == 1


@pytest.mark.parametrize("relpath", ["package-lock.json", "pnpm-lock.yaml"])
@pytest.mark.parametrize(
    "escaped_integrity",
    [
        TWILIO_SHAPED_SRI.replace("sha512-S", r"sha512-\u0053"),
        TWILIO_SHAPED_SRI.replace("sha512-", r"sha512\u002d"),
    ],
)
def test_escaped_provider_signature_inside_checksum_remains_visible(
    relpath, escaped_integrity
):
    if relpath == "package-lock.json":
        src = (
            '{"lockfileVersion":3,"packages":{"node_modules/pkg":'
            f'{{"integrity":"{escaped_integrity}"}}}}}}'
        )
    else:
        pytest.importorskip("yaml")
        src = (
            "lockfileVersion: '9.0'\npackages:\n  'pkg@1.0.0':\n"
            f'    resolution: {{integrity: "{escaped_integrity}"}}\n'
        )

    findings = list(scan_ctx(_ctx_from_source(src + "\n", rel=relpath)))

    assert [finding["provider"] for finding in findings].count("twilio") == 1


@pytest.mark.parametrize(
    "continued_integrity",
    [
        TWILIO_SHAPED_SRI.replace("SK", "S\\\n      K", 1),
        TWILIO_SHAPED_SRI.replace("SK", "\\\n      SK", 1),
    ],
)
def test_multiline_yaml_escape_cannot_hide_provider_signature(
    continued_integrity,
):
    pytest.importorskip("yaml")
    src = (
        "lockfileVersion: '9.0'\npackages:\n  'pkg@1.0.0':\n"
        f'    resolution:\n      integrity: "{continued_integrity}"\n'
    )

    findings = list(scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml")))

    assert [finding["provider"] for finding in findings].count("twilio") == 1


def test_multiline_yaml_scalar_does_not_hide_inline_comment_secret():
    pytest.importorskip("yaml")
    src = f"""lockfileVersion: '9.0'
packages:
  'pkg@1.0.0':
    resolution:
      integrity: | # {NPM_SRI}
        x
"""

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="pnpm-lock.yaml"))
        if finding["provider"] == "generic"
    ]

    assert any(finding["preview"] == "sha5…IA==" for finding in generic)


def test_decoded_provider_deduplication_scales_linearly():
    token_count = 4_000
    decoded_value = "x " + " ".join(
        "SK" + f"{index:032x}" for index in range(token_count)
    )
    src = json.dumps(
        {"lockfileVersion": 3, "metadata": {"integrity": decoded_value}},
        separators=(",", ":"),
    ).replace('"x ', '"\\u0078 ', 1)

    started_at = time.perf_counter()
    findings = list(scan_ctx(_ctx_from_source(src, rel="package-lock.json")))
    elapsed = time.perf_counter() - started_at

    assert [finding["provider"] for finding in findings].count("twilio") == token_count
    assert elapsed < 1.0


def test_escaped_npm_integrity_uses_parser_span():
    escaped_integrity = NPM_SRI.replace("+", r"\u002b")
    src = (
        '{"name":"demo","lockfileVersion":3,"packages":{'
        '"node_modules/pkg":{"integrity":"'
        f'{escaped_integrity}"}}}}}}\n'
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


@pytest.mark.parametrize(
    "relpath,src",
    [
        ("config.json", json.dumps({"integrity": NPM_SRI})),
        ("app.py", f'session_id = "{NPM_SRI}"'),
    ],
)
def test_sri_shape_outside_known_lockfile_context_is_detected(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "src",
    [
        json.dumps(
            {
                "name": "demo",
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": "3",
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3.0,
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "metadata": {"integrity": NPM_SRI},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {"vendor/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 1,
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "dependencies": {"pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 999,
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {"node_modules/../pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {"node_modules/@scope": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "packages": {"node_modules/pkg/metadata": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 1,
                "dependencies": {"..": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 1,
                "dependencies": {"../metadata": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        json.dumps(
            {
                "name": "demo",
                "lockfileVersion": 3,
                "metadata": float("nan"),
                "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            },
            indent=2,
        ),
        f'{{"lockfileVersion": 3, "integrity": "{NPM_SRI}"',
    ],
)
def test_npm_lockfile_requires_valid_structure_before_suppressing(src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert generic


def test_npm_integrity_suppression_handles_cr_only_lines():
    src = json.dumps(
        {
            "name": "demo",
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
        },
        indent=2,
    ).replace("\n", "\r")

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_quoted_secret_key_with_sri_shape_is_detected():
    src = json.dumps(
        {"name": "demo", "lockfileVersion": 3, "api_key": NPM_SRI}, indent=2
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["preview"] == "sha5…IA=="


@pytest.mark.parametrize(
    "secret_key",
    [
        "github_token",
        "client_secret",
        "database_password",
        "private_key",
        "service_credentials",
        "apiKey",
        "apikey",
        "authToken",
        "accessToken",
        "clientSecret",
        "githubToken",
        "openaiApiKey",
        "stripeApiKey",
        "googleApiKey",
        "myPrivateKey",
        "OpenAIApiKey",
        "ServicePrivateKey",
        "clientsecret",
        "refreshtoken",
        "githubtoken",
        "dbpassword",
        "servicecredentials",
        "authbearer",
        "ClientSecret",
        "GitHubToken",
        "DatabasePassword",
        "ServiceCredentials",
        "checksum_service_secret",
        "hash_rotation_token",
        "digest_backup_password",
        "fingerprint_registry_api_key",
    ],
)
def test_compound_quoted_secret_keys_are_detected(secret_key):
    src = json.dumps({secret_key: GENERIC_SECRET}) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="config.json"))
        if finding["provider"] == "generic"
    ]

    assert [(finding["preview"], finding["col"]) for finding in generic] == [
        ("aB3d…Y3zZ", src.index(GENERIC_SECRET))
    ]


@pytest.mark.parametrize(
    "ordinary_key",
    [
        "tokenizer_hash",
        "secretary_id",
        "passwordless_callback",
        "bearerish_value",
        "token_hash",
        "password_hash",
        "password_digest",
        "secret_checksum",
        "api_key_fingerprint",
        "auth_token_hash",
        "authTokenHash",
        "clientSecretHash",
        "accessTokenDigest",
        "githubTokenChecksum",
        "ClientSecretHash",
        "OpenAIApiKeyFingerprint",
        "password_reset_token_hash",
        "secret_value_checksum",
        "api_key_material_fingerprint",
        "private_key_public_fingerprint",
        "credential_value_digest",
        "password_reset_token_hash_v2",
        "secret_value_token_checksum_base64",
        "api_key_material_secret_fingerprint_sha256",
    ],
)
def test_secret_key_markers_require_complete_segments(ordinary_key):
    src = json.dumps({ordinary_key: PURE_ALNUM_SECRET}) + "\n"

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="config.json"))
        if finding["provider"] == "generic"
    ]

    assert generic == []


def test_safe_first_keyed_value_does_not_hide_later_secret():
    src = json.dumps(
        {"password": "A" * 40, "api_key": GENERIC_SECRET}, separators=(",", ":")
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="config.json"))
        if finding["provider"] == "generic"
    ]

    assert [(finding["preview"], finding["col"]) for finding in generic] == [
        ("aB3d…Y3zZ", src.index(GENERIC_SECRET))
    ]


def test_npm_integrity_reused_outside_approved_path_is_not_suppressed():
    src = json.dumps(
        {
            "name": "demo",
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            "metadata": {"integrity": NPM_SRI},
        },
        indent=2,
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "integrity",
    [
        NPM_SRI.replace("sha512-", "SHA512-"),
        NPM_SRI.replace("sha512-", "sha1-"),
        SHA1_SRI,
        NPM_SRI.replace("+", "_"),
        NPM_SRI.replace("sha512-", "md5-"),
        NPM_SRI.replace("sha512-", "sha999-"),
        NPM_SRI + "=",
        NPM_SRI.replace("+", "*"),
        f"  {NPM_SRI}  ",
        f"{NPM_SRI}\n{SHA256_SRI}",
    ],
)
def test_npm_lockfile_rejects_noncanonical_integrity(integrity):
    src = json.dumps(
        {
            "name": "demo",
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": integrity}},
        },
        indent=2,
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "src",
    [
        f'url = "https://registry.invalid/?access_token={NPM_SRI}"',
        f"session={NPM_SRI}",
        f"checksum={NPM_SRI}=",
    ],
)
def test_sri_candidates_next_to_assignment_and_extra_padding_are_detected(src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel="uv.lock"))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "relpath,src",
    [
        ("pnpm-lock.yaml", f"metadata:\n  integrity: {NPM_SRI}\n"),
        ("deno.lock", json.dumps({"metadata": {"integrity": NPM_SRI}})),
        ("flake.lock", json.dumps({"narHash": NPM_SRI})),
    ],
)
def test_unvalidated_lockfile_fields_do_not_suppress_sri(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic


@pytest.mark.parametrize(
    "relpath,src",
    [
        (
            "deno.lock",
            f'{{"version":"5","metadata":{{"integri\\u0074y":"{PURE_ALNUM_SECRET}"}}}}',
        ),
        (
            "flake.lock",
            f'{{"version":7,"metadata":{{"nar\\u0048ash":"{PURE_ALNUM_SECRET}"}}}}',
        ),
        (
            "packages.lock.json",
            '{"version":1,"metadata":{'
            f'"content\\u0048ash":\n"{NPM_SRI.split("-", 1)[1]}"}}}}',
        ),
    ],
)
def test_decoded_wrong_path_checksum_keys_remain_visible(relpath, src):
    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src + "\n", rel=relpath))
        if finding["provider"] == "generic"
    ]

    assert generic


def test_hash_marker_does_not_suppress_generic_secret_on_same_line():
    token = "aB3dE5fG7hI9jK2lM4nO6pQ8rS0-tU1vW2xY3zZ"
    src = f'api_key = "{token}"  # sha256-deadbeef\n'
    ctx = _ctx_from_source(src)

    generic = [f for f in scan_ctx(ctx) if f["provider"] == "generic"]

    assert len(generic) == 1
    assert generic[0]["preview"] == "aB3d…Y3zZ"


def test_json_hash_field_does_not_suppress_later_generic_secret():
    token = "aB3dE5fG7hI9jK2lM4nO6pQ8rS0-tU1vW2xY3zZ"
    src = f'{{"hash": "sha256-deadbeef", "api_key": "{token}"}}\n'
    ctx = _ctx_from_source(src, rel="config.json")

    generic = [f for f in scan_ctx(ctx) if f["provider"] == "generic"]

    assert len(generic) == 1
    assert generic[0]["preview"] == "aB3d…Y3zZ"


@pytest.mark.parametrize("secret_key", ["access_token", "api_key"])
def test_real_secret_beside_valid_integrity_value_is_still_detected(secret_key):
    src = json.dumps(
        {
            "lockfileVersion": 3,
            "packages": {"node_modules/pkg": {"integrity": NPM_SRI}},
            secret_key: GENERIC_SECRET,
        },
        separators=(",", ":"),
    )

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(GENERIC_SECRET)
    assert generic[0]["preview"] == "aB3d…Y3zZ"


@pytest.mark.parametrize(
    "token,provider",
    [
        ("ghp_" + "1234567890abcdef" * 2 + "1234", "github"),
        ("sk_live_" + "a1B2c3D4e5F6g7H8", "stripe"),
    ],
)
def test_provider_secret_in_integrity_field_is_still_detected(token, provider):
    src = f'"integrity": "{token}"\n'
    ctx = _ctx_from_source(src, rel="package-lock.json")
    providers = [f["provider"] for f in scan_ctx(ctx)]
    assert provider in providers


def test_unrecognized_integrity_value_is_still_detected_as_generic():
    token = "aB3dE5fG7hI9jK2lM4nO6pQ8rS0-tU1vW2xY3zZ"
    src = f'"integrity": "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="package-lock.json"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(token)


def test_malformed_sri_value_is_still_detected_as_generic():
    token = "sha512-AbCdEfGh1234567890AbCdEfGh1234567890AABB"
    src = f'  integrity "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="yarn.lock"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(token)


def test_secret_key_context_is_not_suppressed_by_valid_sri_shape():
    token = (
        "sha512-nJhYv8z5ti1j2f7/Bt+4YN+j4/H0uDltKcAx0fBvGG0Fa9JEOv3UJ3e6qb1d5Iq"
        "hvIiqoBs1XqAkONKvgjfG4Q=="
    )
    src = f'api_key = "{token}"\n'

    generic = [
        finding
        for finding in scan_ctx(_ctx_from_source(src, rel="uv.lock"))
        if finding["provider"] == "generic"
    ]

    assert len(generic) == 1
    assert generic[0]["col"] == src.index(token)


def test_many_structured_integrity_values_are_scanned_quickly():
    src = json.dumps(
        {
            "lockfileVersion": 3,
            "packages": {
                f"node_modules/pkg-{index}": {"integrity": NPM_SRI}
                for index in range(2_000)
            },
        },
        separators=(",", ":"),
    )

    started_at = time.perf_counter()
    findings = list(scan_ctx(_ctx_from_source(src, rel="package-lock.json")))
    elapsed = time.perf_counter() - started_at

    assert findings == []
    assert elapsed < 2.0


def test_deep_irrelevant_integrity_metadata_has_bounded_scan_time():
    nested = [{"integrity": "a"} for _ in range(5_000)]
    for _ in range(100):
        nested = {"wrapper": nested}
    src = json.dumps({"lockfileVersion": 3, "metadata": nested}, separators=(",", ":"))

    started_at = time.perf_counter()
    findings = list(scan_ctx(_ctx_from_source(src + "\n", rel="package-lock.json")))
    elapsed = time.perf_counter() - started_at

    assert findings == []
    assert elapsed < 2.0


def test_lockfile_suffix_scanned_for_secrets():
    # Issue #693: .lock files (uv.lock, Cargo.lock, package-lock.json style)
    # were skipped entirely because ".lock" was not in the allowed suffixes.
    src = 'access_token = "aB3dE5fG7hI9jK2lM4nO6pQ8rS0-tU1vW2xY3zZ"\n'
    findings = list(scan_ctx(_ctx_from_source(src, rel="uv.lock")))
    assert any(f["provider"] == "generic" for f in findings)


def test_lockfile_hash_field_still_not_flagged():
    # Checksums inside lockfiles are public integrity data, not secrets.
    src = (
        'hash = "sha256:e3b0c44298fc1c149afbf4c8996fb924'
        '27ae41e4649b934ca495991b7852b855"\n'
    )
    ctx = _ctx_from_source(src, rel="uv.lock")
    generic = [f for f in scan_ctx(ctx) if f["provider"] == "generic"]
    assert generic == []
